services:
  db:
    image: postgres:15-alpine
    container_name: novapay_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: novapay_db
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service-novapay
    container_name: novapay_auth
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:3000
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=novapay_db;Username=postgres;Password=admin"
      JwtSettings__SecretKey: ldskfj34ioji4o3jwefqjiwofj4ijf49i2904i2309i432904
      JwtSettings__Issuer: NovaPayAuthService
      JwtSettings__Audience: NovaPayServices
      JwtSettings__ExpiryInMinutes: "120"
      SmtpSettings__Host: smtp.gmail.com
      SmtpSettings__Port: "465"
      SmtpSettings__Username: eltrabajobienhechokinalito@gmail.com
      SmtpSettings__Password: "wegt znar psjb oesi"
      SmtpSettings__FromEmail: eltrabajobienhechokinalito@gmail.com
      SmtpSettings__FromName: NovaPay
      SmtpSettings__Enabled: "true"
      SmtpSettings__UseImplicitSsl: "true"
      AppSettings__FrontendUrl: http://localhost:5173
      Security__AllowedOrigins__0: "http://localhost:3000"
      Security__AllowedOrigins__1: "http://localhost:3001"
      Security__AllowedOrigins__2: "http://localhost:3002"
      Security__AllowedOrigins__3: "http://localhost:5173"
      Security__AllowedOrigins__4: "http://localhost:5174"

  app-admin:
    build: ./Novapay-admin
    container_name: novapay_app_admin
    ports:
      - "3001:3001"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: novapay_db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_DIALECT: postgres

  app-user:
    build: ./Novapay-user
    container_name: novapay_app_user
    command: sh -c "sleep 5 && node index.js"
    ports:
      - "3002:3002"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: novapay_db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_DIALECT: postgres

  client-admin:
      build: ./client-admin
      container_name: novapay_frontend
      ports:
        - "5173:5173"
      restart: on-failure
      depends_on:
        - auth-service
        - app-admin
        - app-user
      environment:
        VITE_AUTH_URL: http://localhost:3000
        VITE_ADMIN_URL: http://localhost:3001/NovaPay/admin/v1
        VITE_USER_URL: http://localhost:3002

  client-user:
    build: ./client-user-novapay
    container_name: novapay_frontend_user
    ports:
      - "5174:5174"
    restart: on-failure
    depends_on:
      - auth-service
      - app-user
    environment:
      VITE_AUTH_URL: http://localhost:3000
      VITE_USER_URL: http://localhost:3002/NovaPay/v1