services:
  db:
    image: postgres:15-alpine
    container_name: novapay_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: novapay_db
    ports:
      - "5433:5432"

  app-admin:
    build: ./Novapay-admin
    container_name: novapay_app_admin
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: novapay_db

  app-user:
    build: ./Novapay-user
    container_name: novapay_app_user
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: novapay_db
